version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: pguser_dev
      POSTGRES_PASSWORD: 2tZxHFizMpxll5
      POSTGRES_DB: pgdatabase
      
    networks:
        - ets_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
    ets_network:
        external: true
