version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel11-app
    environment:
        APP_NAME: Laravel
        APP_ENV: local
        APP_KEY: base64:nKy3bfQf/STDcTlOExN2BnIqXr9k3VHgV0jTKB3Wna4=
        APP_DEBUG: true
        APP_URL: http://localhost

        APP_LOCALE: en
        APP_FALLBACK_LOCALE: en
        APP_FAKER_LOCALE: en_US

        APP_MAINTENANCE_DRIVER: file
        APP_MAINTENANCE_STORE: database

        PHP_CLI_SERVER_WORKERS: 4

        BCRYPT_ROUNDS: 12

        LOG_CHANNEL: stack
        LOG_STACK: single
        LOG_DEPRECATIONS_CHANNEL: null
        LOG_LEVEL: debug

        DB_CONNECTION: mysql
        DB_HOST: 192.168.4.57
        DB_PORT: 3306
        DB_DATABASE: ets_evaluate_db_aws
        DB_USERNAME: ets_evaluate_user_master
        DB_PASSWORD: 2tZxHFizMpxll5

        BROADCAST_CONNECTION: log
        CACHE_STORE: database
        FILESYSTEM_DISK: local
        QUEUE_CONNECTION: database
        SESSION_DRIVER: database
        SESSION_LIFETIME: 120

        MEMCACHED_HOST: 127.0.0.1

        REDIS_CLIENT: phpredis
        REDIS_HOST: 127.0.0.1
        REDIS_PASSWORD: null
        REDIS_PORT: 6379

        PUSHER_APP_ID: ""
        PUSHER_APP_KEY: ""
        PUSHER_APP_SECRET: ""
        PUSHER_HOST: ""
        PUSHER_PORT: 443
        PUSHER_SCHEME: https
        PUSHER_APP_CLUSTER: mt1
        
        MAIL_MAILER: log
        MAIL_HOST: 127.0.0.1
        MAIL_PORT: 2525
        MAIL_USERNAME: null
        MAIL_PASSWORD: null
        MAIL_ENCRYPTION: null
        MAIL_FROM_ADDRESS: "hello@example.com"
        MAIL_FROM_NAME: "${APP_NAME}"

        VITE_APP_NAME: "${APP_NAME}"
        VITE_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
        VITE_PUSHER_HOST: "${PUSHER_HOST}"
        VITE_PUSHER_PORT: "${PUSHER_PORT}"
        VITE_PUSHER_SCHEME: "${PUSHER_SCHEME}"
        VITE_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"

    ports:
      - "8001:8001"
    volumes:
      - .:/var/www/html
    networks:
      - ets_network

  nginx:
    image: nginx:latest
    container_name: nginx-laravel
    ports:
        - "80:80"
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - .:/var/www/html
    networks:
        - ets_network
    depends_on:
        - app

networks:
    ets_network:
        external: true

