version: "3.8"

services:
    app:
        image: reaksa7236/ets-evaluat-v2:master
        container_name: laravel11-app
        env_file:
            - .env
        networks:
            - ets_network

        ports:
            - "8001:8001"
        volumes:
            - .:/var/www/html

    nginx:
        image: nginx:latest
        container_name: nginx-laravel
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        depends_on:
            - app
        networks:
            - ets_network

networks:
    ets_network:
        external: true
